apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-maven-app
  labels:
    app: java-maven-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-maven-app
  template:
    metadata:
      labels:
        app: java-maven-app
    spec:
      containers:
        - name: java-maven-app
          image: padmandl/myrepo:jma-5.0
          ports:
            - containerPort: 3080

#          env:
#            - name: MONGO_INITDB_ROOT_USERNAME
#              valueFrom:
#                secretKeyRef:
#                  name: mongodb-secret
#                  key: mongo-root-username
#            - name: MONGO_INITDB_ROOT_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: mongodb-secret
#                  key: mongo-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: java-maven-app-service
spec:
  selector:
    app: java-maven-app
  ports:
    - protocol: TCP
      port: 3080
      targetPort: 3080
      