version: '3'
services:
  java-maven-app:
    image: padmandl/myrepo:jma-5.0
    ports:
      - 3090:3090
#    networks:
#      - mynetwork

#  mongodb:
#    image: mongo
#    ports:
#      - 27017:27017
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_ROOT_PASSWORD=password
#    volumes:
#      - mongo-data:/data/db
#    networks:
#      - mynetwork

#  mongo-express:
#    image: mongo-express
#    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
#    ports:
#      - 8070:8081
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
#      - ME_CONFIG_MONGODB_SERVER=mongodb
#    networks:
#      - mynetwork

#volumes:
#  mongo-data:
#    driver: local

#networks:
#  mynetwork:
